### PR TITLE
Fix maven package name + Fix compilation problems

### PR DESCRIPTION
**Pull request by marysaka**

### CODE REVIEW

**Comment by RX14** [comment]
:+1:

**Comment by skyem123** [comment]
Uh...
So I locally pulled this, and it didn't work.
`Exception in thread "main" java.lang.NoClassDefFoundError: uk/co/skyem/projects/Z80emu/Main (wrong name: uk/co/skyem/projects/z80emu/Main)`

**Comment by marysaka** [comment]
@skyem123 BAKA! Just change the main class ><

**Comment by skyem123** [comment]
okay...
While it compiles and works, IntelliJ IDEA is still disliking the fact that the directories and packages have different capitals (red squiggly lines under the package name).

**Comment by skyem123** [comment]
meh... Would it be okay if I just renamed the package to `emuZ80`?

**Comment by skyem123** [comment]
Should be done.
Don't mind the multiple commits...

**Pull request closed without merging**
