### PR TITLE
Improve the build script

### PR DESCRIPTION
**Pull request by marysaka**

### CODE REVIEW

**Comment by RX14** [comment]
Some improvements:
1. Replace `archivesBaseName = 'Z80emu'` with a `settings.gradle` file with `rootProject.name = 'Z80emu'`
2. Use this instead of `sourceCompatibility` and `compileJava.options.encoding`:

``` java
compileJava {
    options.encoding = 'UTF-8'
    sourceCompatibility = 1.8
}
```

**Comment by marysaka** [comment]
It's true, I will fix that

**Comment by skyem123** [comment]
Can you rebase this onto the current master?
^^;

**Comment by RX14** [comment]
cant you?

**Comment by skyem123** [comment]
ah well... The rebasing I did wasn't detected as a merge by GitHub.
"merged" by commit 50b52161e5d8270820f59016e84d0800d400943a

**Comment by RX14** [comment]
It will be detected if you use `git merge --no-ff`. You should always use `git merge --no-ff` for pull requests instead of `git rebase`. You also get to name the merge commit to contain "Merge pull request #9"

**Comment by RX14** [comment]
General guide, although I don't always totally agree with this: https://github.com/agis-/git-style-guide

**Pull request closed without merging**
